version: '3'

services:
  habitat:
    image: ghcr.io/nutberry/artifacts/bricked:latest
    restart: unless-stopped
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - TYPED_DATA={"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"}],"InitMoloch":[{"name":"nonce","type":"uint256"},{"name":"summoner","type":"address"},{"name":"approvedToken","type":"address"},{"name":"periodDuration","type":"uint256"},{"name":"votingPeriod","type":"uint256"},{"name":"gracePeriod","type":"uint256"},{"name":"abortWindow","type":"uint256"},{"name":"dilutionBound","type":"uint256"},{"name":"summoningTime","type":"uint256"}],"SubmitProposal":[{"name":"nonce","type":"uint256"},{"name":"startingPeriod","type":"uint256"},{"name":"title","type":"string"},{"name":"details","type":"string"},{"name":"actions","type":"bytes"}],"SubmitVote":[{"name":"proposalIndex","type":"uint256"},{"name":"uintVote","type":"uint8"}],"ProcessProposal":[{"name":"proposalIndex","type":"uint256"}],"Ragequit":[{"name":"nonce","type":"uint256"},{"name":"sharesToBurn","type":"uint256"}],"Abort":[{"name":"proposalIndex","type":"uint256"}],"UpdateDelegateKey":[{"name":"nonce","type":"uint256"},{"name":"newDelegateKey","type":"address"}]},"domain":{"name":"GovBrick","version":"1"},"primaryTypes":["InitMoloch","SubmitProposal","SubmitVote","ProcessProposal","Ragequit","Abort","UpdateDelegateKey"]}
      - EVENT_CHECK_MS=6000
      - BLOCK_SIZE_THRESHOLD=31000
      - BLOCK_TIME_THRESHOLD=99999999
      - SUBMIT_SOLUTION_THRESHOLD=256
      - MAX_TRANSACTION_SIZE=512
      # Provide these via environment variables or edit in place
      - ROOT_RPC_URL=https://rpc-proxy.fly.dev/https://mainnet.infura.io/v3/$INFURA_KEY
      - PRIV_KEY=$NODE_PK
      - BRIDGE_ADDRESS=$HABITAT_BRIDGE
    volumes:
      - node_data:/opt/node/data
    ports:
      - 8080:8080

volumes:
  node_data:
