name: Coverage

on:
  push:
    branches:
    - master
    - release/*

  pull_request_review_comment:
    types: [created, edited]

jobs:
  coverage:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event.comment.body == '/COVERAGE'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
    - name: Setup
      run: apk add --no-cache git geth bash curl

    - uses: actions/checkout@v2

    - name: Install
      env:
        PAT: ${{ secrets.PAT }}
      run: printf "https://x:"$PAT"@github.com\n" > ~/.git-credentials && git config --global credential.helper store && git config --local credential.helper store && sha1sum ~/.git-credentials && echo $HOME && cat ~/.gitconfig && git clone -v https://github.com/NutBerry/rollup-bricks.git && yarn install --verbose

    - name: Coverage
      run: yarn coverage

    - name: Upload Coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage-report.json
        fail_ci_if_error: true
