name: Coverage

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

  pull_request_review_comment:
    types: [created, edited]

jobs:
  coverage:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event.comment.body == '/COVERAGE'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.PAT }}

    - name: Setup git credentials
      env:
        PAT: ${{ secrets.PAT }}
      run: printf "https://x:"$PAT"@github.com\n" > .env

    - name: Setup
      run: docker-compose up --timeout 1 --exit-code-from dev

    - name: Coverage
      run: docker-compose run dev sh -c 'cd /app && yarn coverage'

    - name: Upload Coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage-report.json
        fail_ci_if_error: true
