name: Publish Landing Page

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build & publish
      run: docker build --build-arg=WEB_PATH=web/ --build-arg=FLY_TOKEN=${{ secrets.FLY_TOKEN }} --build-arg=DOMAIN=${{ secrets.DOMAIN }} -f docker/publishWeb -t tmp .
